# Generated by Django 3.2.7 on 2022-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220414_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
